---
- name: add mongodb apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    state: present

- name: add mongodb apt repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongo_version }} multiverse'
    state: present

- name: install mongodb
  package:
    name: mongodb-org
    state: latest

- name: configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    backup: yes
    owner: root
    group: root
    mode: '0644'
  notify: restart mongod

- name: start mongodb
  service:
    name: mongod
    enabled: yes
    state: started
