---
- name: set up openhim-core container
  docker_container:
    name: openhim-core
    image: jembi/openhim-core:{{ openhim_core_version }}
    state: started
    pull: yes
    restart_policy: unless-stopped
    published_ports:
      # API port
      - "{{ ansible_host }}:8080:8080"
      # HTTPS port
      - "{{ ansible_host }}:5000:5000"
      # HTTP port
      - "{{ ansible_host }}:5001:5001"
    env:
      mongo_url: "mongodb://{{ groups['db'] | join (',') }}/openhim?replicaSet=rs0"
      mongo_atnaUrl: "mongodb://{{ groups['db'] | join (',') }}/openhim?replicaSet=rs0"
      api_authenticationTypes: "[\"token\", \"basic\"]"
- name: configure openhim
  uri:
    method: POST
    url: 'https://{{ groups["app"][0] }}:8080/metadata'
    status_code: 201
    body: '{{ lookup("template", "openhim-insert.json") }}'
    body_format: json
    user: "root@openhim.org"
    password: "openhim-password"
    force_basic_auth: yes
    validate_certs: no
  tags:
    - configuration
