---
- set_fact: do_token="{{ lookup('env', 'DO_API_TOKEN')}}"

- set_fact: ssh_key_name="{{ lookup('env', 'SSH_KEY_NAME')}}"

- name: ensure ssh key exists and get the key id
  digital_ocean:
    state: present
    command: ssh
    name: '{{ ssh_key_name }}'
  register: my_ssh_key
