---
- set_fact: do_token="{{ lookup('env', 'DO_API_TOKEN')}}"

- set_fact: ssh_key_name="{{ lookup('env', 'SSH_KEY_NAME')}}"

- name: ensure ssh key exists and get the key
  digital_ocean:
    state: present
    command: ssh
    name: '{{ ssh_key_name }}'
  register: my_ssh_key

- debug:
    msg: 'this be the id {{ my_ssh_key.ssh_key.id }}'

- name: create droplets for mongo instances
  digital_ocean:
    state: present
    command: droplet
    name: '{{ item.name }}'
    size_id: 512mb
    ssh_key_ids: '{{ my_ssh_key.ssh_key.id }}'
    region_id: fra1
    image_id: ubuntu-18-04-x64
    api_token: '{{ do_token }}'
  loop: '{{ mongoInstances }}'

- name: create droplets for openhim instances
  digital_ocean:
        state: present
        command: droplet
        name: '{{ item.name }}'
        unique_name: yes
        size_id: 512mb
        ssh_key_ids: '{{ my_ssh_key.ssh_key.id }}'
        region_id: fra1
        image_id: ubuntu-18-04-x64
        api_token: '{{ do_token }}'
  loop: '{{ openhimInstances }}'

- name: create a droplet for the server that runs the test
  digital_ocean:
        state: present
        command: droplet
        name: openhim-perfomance-test-server
        size_id: 512mb
        ssh_key_ids: '{{ my_ssh_key.ssh_key.id }}'
        region_id: fra1
        image_id: ubuntu-18-04-x64
        api_token: '{{ do_token }}'
