---
- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: install docker
  package:
    name: docker-ce
    state: present

- name: start docker
  service:
    name: docker
    enabled: yes
    state: started

- name: install python pip
  package:
    name: python-pip
    state: present

- name: install docker from pip
  pip:
    name: docker
    state: present
