- hosts: localhost
  tasks:
    - set_fact: do_token="{{ lookup('env','DO_API_TOKEN') }}"

    - debug: msg="Droplet name is {{ item.split(' ')[0] }}"
      with_lines: cat xhosts

    - name: destroy droplets
      digital_ocean: >
        state=absent
        command=droplet
        name={{ item.split(' ')[0] }}
        unique_name=yes
        api_token={{ do_token }}
      with_items: cat xhosts
