---
- name: create droplets for mediator instance
  digital_ocean:
        state: present
        command: droplet
        name: '{{ item.name }}'
        unique_name: yes
        size_id: '{{ size_id }}'
        ssh_key_ids: '{{ my_ssh_key.ssh_key.id }}'
        region_id: '{{ region_ID }}'
        image_id: '{{ image_ID }}'
        api_token: '{{ do_token }}'
  register: mediatorDroplets
  loop: '{{ mediatorInstances }}'

- name: install Python 2.x
  raw: which python || sudo apt-get update && sudo apt-get install -qq -y python-simplejson
  register: python_check
  changed_when: not python_check.stdout is search('/usr/bin/python')

- name: install pip
  apt:
    name: python-pip
    state: present
    update_cache: yes
